language: ruby
rvm:
  - 2.6.5
install:
  - bundle install
  - nvm install 10
  - npm i -g yarn
  - yarn
dist: xenail
addons:
  chrome: stable
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec